### ISSUE TITLE
Windows compatability

### ISSUE THREAD

**Issue by Steve0Greatness** [ajskateboarder/scratch-git#2]
Windows cannot easily run BASH scripts, the scripting language of Windows PowerShell(terminal) is instead PowerShell(script format)(File ending: `.ps1`).

**Comment by ajskateboarder** [comment]
I might make a batch script instead because you don't have to deal with any weird script execution permissions

**Comment by ajskateboarder** [comment]
> I might make a batch script instead because you don't have to deal with any weird script execution permissions

Turns out Batch scripting is the biggest pain of all time. There is now a work-in-progress Python script to do everything cross-platform. Sorry for the delay :rofl:
