### ISSUE TITLE
Popup Does not Fully Close when Close is Clicked

### ISSUE THREAD

**Issue by Steve0Greatness** [ajskateboarder/scratch-git#21]
OS: Windows
Version: 0.0.50

I'm not sure if this is a bug on other operating systems, but when you click the "Close" button on the popup for Scratch-Git, it doesn't fully close; rather: it goes below the stage, but over the code editor, and stays visible until right clicked.

**Comment by ajskateboarder** [comment]
I've noticed the modal go below the stage on Linux (Ubuntu 20.04) too, but it doesn't seem to cause any issues there. Will fix

**Comment by ajskateboarder** [comment]
Fixed by https://github.com/ajskateboarder/scratch-git/commit/5778e1dd4aeb847a5397b65bd816c2a23e21065d
