### ISSUE TITLE
Save Action not Triggered with CTRL-S

### ISSUE THREAD

**Issue by Steve0Greatness** [ajskateboarder/scratch-git#25]
Pressing CTRL-S doesn't seem to trigger the "unzip" and "get-changed-sprites" commands

**Comment by ajskateboarder** [comment]
I'm pretty sure it works by pressing <kbd>Ctrl/Cmd + Shift + S</kbd> (I haven't tested that recently), but that's not really too intuitive, now that I think about it. I'll consider this

**Comment by ajskateboarder** [comment]
Fixed (?) by https://github.com/ajskateboarder/scratch-git/commit/ecd00315bae55d9876be106371e61df321f01709 - Ctrl+S can be used directly now
