### ISSUE TITLE
How do I unistall it?

### ISSUE THREAD

**Issue by EmimalayaYT** [ajskateboarder/scratch-git#59]
I tried to use it, didn't understand it. The popup is annoying so I want to unistall it. How do I do it?

**Comment by ajskateboarder** [comment]
Open a project that you made with scratch.git, go to Git -> Settings, and click Uninstall

**Comment by EmimalayaYT** [comment]
> Open a project that you made with scratch.git, go to Git -> Settings, and click Uninstall

That is the thing, I don't have any project that uses scratch.git. I tried but I couldn't make it work, but now I want to unistall it and I can't. I also tried unistalling turbowarp and installing it again but it didn't leave.

**Comment by ajskateboarder** [comment]
In that case, click on the ? in the top-right corner, go to Desktop Settings -> Open User Data, and remove "userscript.js"

**Comment by EmimalayaYT** [comment]
> In that case, click on the ? in the top-right corner, go to Desktop Settings -> Open User Data, and remove "userscript.js"

Thanks! that worked : 3
